[build]
build-std = false
xargo = false
zig = false
default-target = "x86_64-unknown-linux-gnu"
pre-build = [
    "apt-get update && apt-get --assume-yes install libssl-dev libsmbclient-dev cmake git",
]
